spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luck_draw?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 19880806
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 100000
    password: 123456

mybatis:
  mapper-locations: classpath:/mybatis/**.xml

server:
  port: 8181
